export const tableData=[{
    id:1,
    size: "7.7 × 74.7 × 158.5 میلی‌متر",
    sim:"سایز نانو (8.8 × 12.3 میلی‌متر)" ,
    wight: "166 گرم",
    body:"قاب جلو شیشه\n" +
        "قاب پشت پلاستیک",
    attrebute:"مناسب عکاسی , فبلت , مجهز به حس‌گر اثرانگشت , مناسب عکاسی سلفی",
    chip:"Exynos 9610 (10nm) CPU",
    cpu:"Quad-core Cortex-A73 + Quad-core Cortex-A53",
    cpuV:"64 بیت",
    cpuF:"2.3 و 1.7 گیگاهرتز",
    gpu:"Mali-G72 MP3 GPU",
    rom:"128 گیگابایت",
    ram:"4 گیگابایت",
    supportMsd:"microSD",
    supportSdMax:"1 ترابایت",
    display:"Super AMOLED",
    displaySize:"6.06.4 اینچ",
    resolotion:"2340 × 1080 پیکسل",
    pixels:"403 پیکسل بر هر اینچ",
    gourd:"Corning Gorilla Glass 3",
    other:"نسبت تصویر: 19.5:9",
    network: "2G , 3G , 4G",
    n2G:"GSM 850 / 900 / 1800 / 1900",
    n3G:"HSDPA 850 / 900 / 1900 / 2100",
    n4G:"LTE band 1|2100, 3|1800, 5|850, 7|2600, 8|900, 20|800, 38|2600, 40|2300, 41|2500",
    transfer:"GPRS , EDGE , Wi-Fi , بلوتوث , رادیو",
    wifi:"Wi-Fi 802.11 b/g/n\n" +
        "WiFi Direct\n" +
        "Hotspot",
    radio:"FM radio",
    blow:"نسخه 5.0",
    input:"USB Type-C 1.0 v2.0",
    cameraR:"25.0 مگاپیکسل",
    flash:"LED",
    cameraO:"دارای سه حسگر دوربین\n" +
        "حسگر اول از نوع Wide با رزولوشن 25 مگاپیکسل، دریچه‌ی دیافراگم f/1.7، فاصله کانونی لنز 26 میلی‌متر (Focal Length 26 mm)، و مجهز به فناوری فوکوس اتوماتیک از نوع PDAF\n" +
        "حسگر دوم از نوع UltraWide با رزولوشن 8 مگاپیکسل، دریچه‌ی دیافراگم f/2.2 و فاصله کانونی لنز 13 میلی‌متر (Focal Length 13 mm)\n" +
        "حسگر سوم از نوع حسگر عمق با رزولوشن 5 مگاپیکسل، دریچه‌ی دیافراگم f/2.2\n" +
        "قابلیت ثبت موقعیت جغرافیایی عکس‌ها و فیلم‌ها (Geo-Tagging)\n" +
        "قابلیت فوکوس با اشاره روی سوژه (Touch Focus)\n" +
        "قابلیت تشخیص چهره (Face Detection)\n" +
        "قابلیت عکاسی پانوراما (Panorama)\n" +
        "قابلیت عکاسی HDR",
    cameraVideo:"رزولوشن 1080 × 1920 و سرعت 30 فریم بر ثانیه (1080p@30FPS)",
    cameraSelf:"حسگری با رزولوشن 25 مگاپیکسل، دریچه‌ی دیافراگم f/2.0، فاصله کانونی لنز 25 میلی‌متر (Focal Length 25 mm)",
    OS:"Android",
    OSV:"Pie 9.0",
    videoSupport:"MP4 , XviD , WMV , H.264 , H.263 , H.265",
    musicSupport:"MP3 , WMA , WAV , Flac",
    battery:"باتری لیتیوم پلیمری با ظرفیت 4000 میلی آمپر ساعت",
    otherBattery:"قابلیت شارژ سریع با توان 15 وات",
    inBox:"دفترچه‌ راهنما , کابل USB , شارژر",
},{
    id:2,
    size: "7.7 × 74.7 × 180.5 میلی‌متر",
    sim:"سایز نانو (8.8 × 12.3 میلی‌متر)" ,
    wight: "170 گرم",
    body:"",
    attrebute:"",
    chip:"",
    cpu:"",
    cpuV:"",
    cpuF:"",
    gpu:"",
    rom:"",
    ram:"",
    supportMsd:"",
    supportSdMax:"",
    display:"",
    displaySize:"",
    resolotion:"",
    pixels:"",
    gourd:"",
    other:"",
    network:"",
    n2G:"",
    n3G:"",
    n4G:"",
    transfer:"",
    wifi:"",
    radio:"",
    blow:"",
    input:"",
    cameraR:"",
    flash:"",
    cameraO:"",
    cameraVideo:"",
    cameraSelf:"",
    OS:"",
    OSV:"",
    videoSupport:"",
    musicSupport:"",
    battery:"",
    otherBattery:"",
    inBox:"",
},{
    id:3,
    size: "7.7 × 74.7 × 180.5 میلی‌متر",
    sim:"سایز نانو (8.8 × 12.3 میلی‌متر)" ,
    wight: "170 گرم",
    body:"قاب جلو شیشه\n" +
        "قاب پشت پلاستیک",
    attrebute:"مناسب عکاسی , فبلت , مجهز به حس‌گر اثرانگشت , مناسب عکاسی سلفی",
    chip:"Exynos 9610 (10nm) CPU",
    cpu:"Quad-core Cortex-A73 + Quad-core Cortex-A53",
    cpuV:"64 بیت",
    cpuF:"2.3 و 1.7 گیگاهرتز",
    gpu:"Mali-G72 MP3 GPU",
    rom:"128 گیگابایت",
    ram:"4 گیگابایت",
    supportMsd:"microSD",
    supportSdMax:"1 ترابایت",
    display:"Super AMOLED",
    displaySize:"6.06.4 اینچ",
    resolotion:"2340 × 1080 پیکسل",
    pixels:"403 پیکسل بر هر اینچ",
    gourd:"Corning Gorilla Glass 3",
    other:"نسبت تصویر: 19.5:9",
    network: "2G , 3G , 4G",
    n2G:"GSM 850 / 900 / 1800 / 1900",
    n3G:"HSDPA 850 / 900 / 1900 / 2100",
    n4G:"LTE band 1|2100, 3|1800, 5|850, 7|2600, 8|900, 20|800, 38|2600, 40|2300, 41|2500",
    transfer:"GPRS , EDGE , Wi-Fi , بلوتوث , رادیو",
    wifi:"Wi-Fi 802.11 b/g/n\n" +
        "WiFi Direct\n" +
        "Hotspot",
    radio:"FM radio",
    blow:"نسخه 5.0",
    input:"USB Type-C 1.0 v2.0",
    cameraR:"25.0 مگاپیکسل",
    flash:"LED",
    cameraO:"دارای سه حسگر دوربین\n" +
        "حسگر اول از نوع Wide با رزولوشن 25 مگاپیکسل، دریچه‌ی دیافراگم f/1.7، فاصله کانونی لنز 26 میلی‌متر (Focal Length 26 mm)، و مجهز به فناوری فوکوس اتوماتیک از نوع PDAF\n" +
        "حسگر دوم از نوع UltraWide با رزولوشن 8 مگاپیکسل، دریچه‌ی دیافراگم f/2.2 و فاصله کانونی لنز 13 میلی‌متر (Focal Length 13 mm)\n" +
        "حسگر سوم از نوع حسگر عمق با رزولوشن 5 مگاپیکسل، دریچه‌ی دیافراگم f/2.2\n" +
        "قابلیت ثبت موقعیت جغرافیایی عکس‌ها و فیلم‌ها (Geo-Tagging)\n" +
        "قابلیت فوکوس با اشاره روی سوژه (Touch Focus)\n" +
        "قابلیت تشخیص چهره (Face Detection)\n" +
        "قابلیت عکاسی پانوراما (Panorama)\n" +
        "قابلیت عکاسی HDR",
    cameraVideo:"رزولوشن 1080 × 1920 و سرعت 30 فریم بر ثانیه (1080p@30FPS)",
    cameraSelf:"سگری با رزولوشن 25 مگاپیکسل، دریچه‌ی دیافراگم f/2.0، فاصله کانونی لنز 25 میلی‌متر (Focal Length 25 mm)",
    OS:"Android",
    OSV:"Pie 9.0",
    videoSupport:"MP4 , XviD , WMV , H.264 , H.263 , H.265",
    musicSupport:"MP3 , WMA , WAV , Flac",
    battery:"اتری لیتیوم پلیمری با ظرفیت 4000 میلی آمپر ساعت",
    otherBattery:"قابلیت شارژ سریع با توان 15 وات",
    inBox:"دفترچه‌ راهنما , کابل USB , شارژر",
},{
    id:2,
    size: "7.7 × 74.7 × 180.5 میلی‌متر",
    sim:"سایز نانو (8.8 × 12.3 میلی‌متر)" ,
    wight: "170 گرم",
    body:"",
    attrebute:"",
    chip:"",
    cpu:"",
    cpuV:"",
    cpuF:"",
    gpu:"",
    rom:"",
    ram:"",
    supportMsd:"",
    supportSdMax:"",
    display:"",
    displaySize:"",
    resolotion:"",
    pixels:"",
    gourd:"",
    other:"",
    network:"",
    n2G:"",
    n3G:"",
    n4G:"",
    transfer:"",
    wifi:"",
    radio:"",
    blow:"",
    input:"",
    cameraR:"",
    flash:"",
    cameraO:"",
    cameraVideo:"",
    cameraSelf:"",
    OS:"",
    OSV:"",
    videoSupport:"",
    musicSupport:"",
    battery:"",
    otherBattery:"",
    inBox:"",
},{
    id:2,
    size: "",
    sim:"" ,
    wight: "",
    body:"",
    attrebute:"",
    chip:"",
    cpu:"",
    cpuV:"",
    cpuF:"",
    gpu:"",
    rom:"",
    ram:"",
    supportMsd:"",
    supportSdMax:"",
    display:"",
    displaySize:"",
    resolotion:"",
    pixels:"",
    gourd:"",
    other:"",
    network:"",
    n2G:"",
    n3G:"",
    n4G:"",
    transfer:"",
    wifi:"",
    radio:"",
    blow:"",
    input:"",
    cameraR:"",
    flash:"",
    cameraO:"",
    cameraVideo:"",
    cameraSelf:"",
    OS:"",
    OSV:"",
    videoSupport:"",
    musicSupport:"",
    battery:"",
    otherBattery:"",
    inBox:"",
},{
    id:2,
    size: "",
    sim:"" ,
    wight: "",
    body:"",
    attrebute:"",
    chip:"",
    cpu:"",
    cpuV:"",
    cpuF:"",
    gpu:"",
    rom:"",
    ram:"",
    supportMsd:"",
    supportSdMax:"",
    display:"",
    displaySize:"",
    resolotion:"",
    pixels:"",
    gourd:"",
    other:"",
    network:"",
    n2G:"",
    n3G:"",
    n4G:"",
    transfer:"",
    wifi:"",
    radio:"",
    blow:"",
    input:"",
    cameraR:"",
    flash:"",
    cameraO:"",
    cameraVideo:"",
    cameraSelf:"",
    OS:"",
    OSV:"",
    videoSupport:"",
    musicSupport:"",
    battery:"",
    otherBattery:"",
    inBox:"",
},{
    id:2,
    size: "",
    sim:"" ,
    wight: "",
    body:"",
    attrebute:"",
    chip:"",
    cpu:"",
    cpuV:"",
    cpuF:"",
    gpu:"",
    rom:"",
    ram:"",
    supportMsd:"",
    supportSdMax:"",
    display:"",
    displaySize:"",
    resolotion:"",
    pixels:"",
    gourd:"",
    other:"",
    network:"",
    n2G:"",
    n3G:"",
    n4G:"",
    transfer:"",
    wifi:"",
    radio:"",
    blow:"",
    input:"",
    cameraR:"",
    flash:"",
    cameraO:"",
    cameraVideo:"",
    cameraSelf:"",
    OS:"",
    OSV:"",
    videoSupport:"",
    musicSupport:"",
    battery:"",
    otherBattery:"",
    inBox:"",
},{
    id:2,
    size: "",
    sim:"" ,
    wight: "",
    body:"",
    attrebute:"",
    chip:"",
    cpu:"",
    cpuV:"",
    cpuF:"",
    gpu:"",
    rom:"",
    ram:"",
    supportMsd:"",
    supportSdMax:"",
    display:"",
    displaySize:"",
    resolotion:"",
    pixels:"",
    gourd:"",
    other:"",
    network:"",
    n2G:"",
    n3G:"",
    n4G:"",
    transfer:"",
    wifi:"",
    radio:"",
    blow:"",
    input:"",
    cameraR:"",
    flash:"",
    cameraO:"",
    cameraVideo:"",
    cameraSelf:"",
    OS:"",
    OSV:"",
    videoSupport:"",
    musicSupport:"",
    battery:"",
    otherBattery:"",
    inBox:"",
},{
    id:2,
    size: "",
    sim:"" ,
    wight: "",
    body:"",
    attrebute:"",
    chip:"",
    cpu:"",
    cpuV:"",
    cpuF:"",
    gpu:"",
    rom:"",
    ram:"",
    supportMsd:"",
    supportSdMax:"",
    display:"",
    displaySize:"",
    resolotion:"",
    pixels:"",
    gourd:"",
    other:"",
    network:"",
    n2G:"",
    n3G:"",
    n4G:"",
    transfer:"",
    wifi:"",
    radio:"",
    blow:"",
    input:"",
    cameraR:"",
    flash:"",
    cameraO:"",
    cameraVideo:"",
    cameraSelf:"",
    OS:"",
    OSV:"",
    videoSupport:"",
    musicSupport:"",
    battery:"",
    otherBattery:"",
    inBox:"",
},{
    id:2,
    size: "",
    sim:"" ,
    wight: "",
    body:"",
    attrebute:"",
    chip:"",
    cpu:"",
    cpuV:"",
    cpuF:"",
    gpu:"",
    rom:"",
    ram:"",
    supportMsd:"",
    supportSdMax:"",
    display:"",
    displaySize:"",
    resolotion:"",
    pixels:"",
    gourd:"",
    other:"",
    network:"",
    n2G:"",
    n3G:"",
    n4G:"",
    transfer:"",
    wifi:"",
    radio:"",
    blow:"",
    input:"",
    cameraR:"",
    flash:"",
    cameraO:"",
    cameraVideo:"",
    cameraSelf:"",
    OS:"",
    OSV:"",
    videoSupport:"",
    musicSupport:"",
    battery:"",
    otherBattery:"",
    inBox:"",
}
];